import { mkdir, mkdtemp, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { Pool } from 'pg';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { DeterministicEmbeddingClient } from '../../src/modules/public-answer/infrastructure/fixture/deterministic-embedding-client.js';
import { canonicalProviderJson, providerChecksum } from '../../src/modules/public-answer/infrastructure/openai/provider-json.js';
import { CancellablePgQueryRunner } from '../../src/modules/public-answer/infrastructure/postgres/cancellable-pg-query-runner.js';
import { PostgresHybridRetriever } from '../../src/modules/public-answer/infrastructure/postgres/postgres-hybrid-retriever.js';
import { createProviderEmbeddingAuthorities, PostgresAnswerReleaseIndexer, prepareEmbeddingSet } from '../../src/modules/public-answer/infrastructure/postgres/postgres-answer-release-indexer.js';
import { runPostgresMigrations } from '../../src/modules/public-answer/infrastructure/postgres/postgres-migrations.js';
import { verifyPublicAnswerPurge } from '../../src/tombstone-public-answer.js';

const databaseUrl=process.env.FORM_THOUGHT_TEST_DATABASE_URL;if(!databaseUrl)throw new Error('FORM_THOUGHT_TEST_DATABASE_URL is required');let pool:Pool;const roots:string[]=[];
beforeEach(async()=>{pool=new Pool({connectionString:databaseUrl,max:8});await pool.query('DROP SCHEMA IF EXISTS public CASCADE');await pool.query('CREATE SCHEMA public');await runPostgresMigrations(pool);});
afterEach(async()=>{await pool.query('DROP SCHEMA IF EXISTS public CASCADE');await pool.query('CREATE SCHEMA public');await pool.end();const{rm}=await import('node:fs/promises');await Promise.all(roots.splice(0).map((root)=>rm(root,{recursive:true,force:true})));});
async function named(root:string,value:unknown){const bytes=`${canonicalProviderJson(value)}\n`;const hash=providerChecksum(Buffer.from(bytes));const file=`${hash.slice(7)}.json`;await writeFile(join(root,file),bytes);return{hash,file};}

async function setup(){
  const receiptRoot=await mkdtemp(join(tmpdir(),'purge-receipts-'));roots.push(receiptRoot);const answerRoot=await mkdtemp(join(tmpdir(),'purge-answers-'));roots.push(answerRoot);
  const affectedContent='a'.repeat(64),affectedAnswer='b'.repeat(64),replacementContent='c'.repeat(64),replacementAnswer='d'.repeat(64),bindingId='44444444-4444-4444-8444-444444444444';
  const entityId='articles/example',reason='legal-removal',createdAt='2026-08-30T00:00:00.000Z',verifiedAt='2026-08-30T00:00:00.000Z',backupExpiresAt='2099-09-30T00:00:00.000Z';const tombstoneHash=providerChecksum({schemaVersion:1,entityKind:'record',entityId,reasonCode:reason,createdAt});
  await pool.query("INSERT INTO public_answer_tombstones(entity_kind,entity_id,reason_code,created_at) VALUES('record',$1,$2,$3::timestamptz)",[entityId,reason,createdAt]);
  await pool.query(`INSERT INTO public_answer_release_bindings(binding_id,content_release_id,answer_release_id,content_manifest_hash,answer_manifest_hash,answer_artifact_hash,embedding_model,embedding_dimensions,embedding_source,embedding_receipt_hash,chunk_count,index_checksum,state,created_at,activated_at) VALUES($1,$2,$3,$4,$5,$6,'text-embedding-3-large',3072,'fixture',$7,0,$8,'active',now(),now())`,[bindingId,replacementContent,replacementAnswer,`sha256:${'1'.repeat(64)}`,`sha256:${'8'.repeat(64)}`,`sha256:${'9'.repeat(64)}`,`sha256:${'6'.repeat(64)}`,`sha256:${'7'.repeat(64)}`]);
  const backup={schemaVersion:1,entityKind:'record',entityId,tombstoneHash,affectedContentReleaseId:affectedContent,affectedAnswerReleaseId:affectedAnswer,affectedAnswerManifestHash:`sha256:${'2'.repeat(64)}`,affectedAnswerArtifactHash:`sha256:${'3'.repeat(64)}`,backupOwnerId:'owner:archive',backupSetId:'set:2026-08',backupDisposition:'expires',backupExpiresAt,verifiedAt,custodianIdentityHash:`sha256:${'4'.repeat(64)}`,verifierIdentityHash:`sha256:${'5'.repeat(64)}`,externalEvidenceChecksum:`sha256:${'6'.repeat(64)}`};const b=await named(receiptRoot,backup);
  const purge={schemaVersion:1,entityKind:'record',entityId,tombstoneHash,affectedContentReleaseId:affectedContent,affectedAnswerReleaseId:affectedAnswer,affectedAnswerManifestHash:backup.affectedAnswerManifestHash,affectedAnswerArtifactHash:backup.affectedAnswerArtifactHash,releaseDirectoryDisposition:'removed',removedArtifactFileChecksums:[],backupEvidenceFile:b.file,backupEvidenceChecksum:b.hash,backupOwnerId:backup.backupOwnerId,backupSetId:backup.backupSetId,backupDisposition:backup.backupDisposition,backupExpiresAt,verifiedAt,custodianIdentityHash:backup.custodianIdentityHash,verifierIdentityHash:backup.verifierIdentityHash,externalEvidenceChecksum:`sha256:${'7'.repeat(64)}`};const p=await named(receiptRoot,purge);
  const receipt={schemaVersion:1,entityKind:'record',entityId,tombstoneHash,affectedContentReleaseId:affectedContent,affectedAnswerReleaseId:affectedAnswer,affectedAnswerManifestHash:backup.affectedAnswerManifestHash,affectedAnswerArtifactHash:backup.affectedAnswerArtifactHash,replacementContentReleaseId:replacementContent,replacementAnswerReleaseId:replacementAnswer,replacementAnswerManifestHash:`sha256:${'8'.repeat(64)}`,replacementAnswerArtifactHash:`sha256:${'9'.repeat(64)}`,replacementBindingId:bindingId,purgeEvidenceFile:p.file,backupEvidenceFile:b.file,artifactPurgeEvidenceChecksum:p.hash,backupEvidenceChecksum:b.hash,backupExpiresAt,verifiedAt,verifierIdentityHash:backup.verifierIdentityHash};const d=await named(receiptRoot,receipt);
  const snapshot={bindingId,contentReleaseId:replacementContent,answerReleaseId:replacementAnswer,corpusApprovalHash:`sha256:${'f'.repeat(64)}`,chunkCount:0,normalizerVersion:'nfkc-lower-hangul-ngram-v1',embeddingSource:'fixture',embeddingReceiptHash:`sha256:${'6'.repeat(64)}`,tombstones:new Set([`record:${entityId}`]),evidenceById:new Map(),chunkById:new Map(),chunkChecksumById:new Map(),isBoundTo:()=>true,evidenceFor:()=>[] } as any;
  const input={pool,catalog:{snapshot:async()=>snapshot} as any,retriever:new PostgresHybridRetriever(new DeterministicEmbeddingClient('test'),new CancellablePgQueryRunner(pool)),config:{deletionReceiptRoot:receiptRoot,answerReleaseRoot:answerRoot} as any,receiptPath:join(receiptRoot,d.file),signal:new AbortController().signal,authorityReader:async()=>({answer:{contentReleaseId:replacementContent,answerReleaseId:replacementAnswer,manifestHash:receipt.replacementAnswerManifestHash,artifactHash:receipt.replacementAnswerArtifactHash}} as any)};
  return{input,answerRoot,affectedContent,affectedAnswer,bindingId,d};
}

describe('purge verification acceptance',()=>{
  it('rejects retained affected bytes and an old/non-current replacement binding',async()=>{const first=await setup();await mkdir(join(first.answerRoot,first.affectedContent,first.affectedAnswer),{recursive:true});await expect(verifyPublicAnswerPurge(first.input)).rejects.toThrow(/bytes remain/u);const{rm}=await import('node:fs/promises');await rm(join(first.answerRoot,first.affectedContent),{recursive:true});await pool.query("UPDATE public_answer_release_bindings SET state='retired' WHERE binding_id=$1",[first.bindingId]);await expect(verifyPublicAnswerPurge(first.input)).rejects.toThrow(/active-index/u);});
  it('fails closed when a fresh purge snapshot omits the normalizer authority',async()=>{const value=await setup();const snapshot=await value.input.catalog.snapshot(value.input.signal);value.input.catalog={snapshot:async()=>({...snapshot,normalizerVersion:undefined})} as any;await expect(verifyPublicAnswerPurge(value.input)).rejects.toThrow(/normalizer/u);});
  it('verifies nonempty-to-empty authority and strict-reopens the exact receipt idempotently',async()=>{const value=await setup();const first=await verifyPublicAnswerPurge(value.input);const second=await verifyPublicAnswerPurge(value.input);expect(second).toEqual(first);expect(first.deletionReceiptHash).toBe(value.d.hash);expect((await pool.query('SELECT count(*)::int AS count FROM public_answer_deletion_receipts')).rows[0].count).toBe(1);});
  it('rejects a post-success reintroduction and leaves the replacement binding current',async()=>{
    const value=await setup();
    await verifyPublicAnswerPurge(value.input);
    const release={contentReleaseId:'e'.repeat(64),answerReleaseId:'f'.repeat(64),manifestHash:`sha256:${'a'.repeat(64)}`,artifactHash:`sha256:${'b'.repeat(64)}`,corpusApprovalHash:`sha256:${'c'.repeat(64)}`,manifest:{identity:{contentManifestHash:`sha256:${'d'.repeat(64)}`,normalizerVersion:'nfkc-lower-hangul-ngram-v1'}},chunks:[{chunkId:'1'.repeat(64),recordId:'articles/example',canonicalPath:'/articles/example/'}],evidence:[{evidenceId:'2'.repeat(64),chunkId:'1'.repeat(64),recordId:'articles/example'}],indexInputs:[{chunkId:'1'.repeat(64),chunkChecksum:`sha256:${'3'.repeat(64)}`,recordId:'articles/example',canonicalPath:'/articles/example/',title:'Example',headingPath:['H'],text:'public text',searchText:'public text'}]} as any;
    const prepared=await prepareEmbeddingSet(release,new DeterministicEmbeddingClient('test'),new AbortController().signal);
    const authorities=createProviderEmbeddingAuthorities(release,prepared,{providerDataControlReceiptHash:`sha256:${'4'.repeat(64)}`,providerPricingReceiptHash:`sha256:${'5'.repeat(64)}`,createdAt:'2026-08-30T00:00:00.000Z',completedAt:'2026-08-30T00:00:01.000Z'});
    await expect(new PostgresAnswerReleaseIndexer('production').activate(release,prepared,authorities.activation,pool,new AbortController().signal,authorities.durable)).rejects.toThrow(/reintroduces/u);
    expect((await pool.query("SELECT binding_id FROM public_answer_release_bindings WHERE state='active'")).rows).toEqual([{binding_id:value.bindingId}]);
  });
  it('waits behind the global lock and leaves the replacement binding current',async()=>{const value=await setup();const blocker=await pool.connect();await blocker.query('BEGIN');await blocker.query("SELECT pg_advisory_xact_lock(hashtextextended('form-thought:public-answer:global-activation:v1',0))");let settled=false;const pending=verifyPublicAnswerPurge(value.input).then((result)=>{settled=true;return result;});await new Promise((accept)=>setTimeout(accept,50));expect(settled).toBe(false);await blocker.query('COMMIT');blocker.release();await expect(pending).resolves.toMatchObject({deletionReceiptHash:value.d.hash});expect((await pool.query("SELECT binding_id FROM public_answer_release_bindings WHERE state='active'")).rows).toEqual([{binding_id:value.bindingId}]);});
});
