import { mkdtemp, symlink, writeFile } from 'node:fs/promises'; import { tmpdir } from 'node:os'; import { join } from 'node:path'; import { afterEach, describe, expect, it } from 'vitest';
import { canonicalProviderJson, providerChecksum } from '../src/modules/public-answer/infrastructure/openai/provider-json.js';
import { readBackupExpiryEvidence } from '../src/modules/public-answer/infrastructure/release/backup-expiry-evidence.js';
const roots:string[]=[]; afterEach(async()=>{const {rm}=await import('node:fs/promises');await Promise.all(roots.splice(0).map(r=>rm(r,{recursive:true,force:true})));});
export function backupValue(){return {schemaVersion:1,entityKind:'record',entityId:'articles/example',tombstoneHash:`sha256:${'1'.repeat(64)}`,affectedContentReleaseId:'a'.repeat(64),affectedAnswerReleaseId:'b'.repeat(64),affectedAnswerManifestHash:`sha256:${'2'.repeat(64)}`,affectedAnswerArtifactHash:`sha256:${'3'.repeat(64)}`,backupOwnerId:'owner:archive',backupSetId:'set:2026-08',backupDisposition:'expires',backupExpiresAt:'2026-09-30T00:00:00.000Z',verifiedAt:'2026-08-30T00:00:00.000Z',custodianIdentityHash:`sha256:${'4'.repeat(64)}`,verifierIdentityHash:`sha256:${'5'.repeat(64)}`,externalEvidenceChecksum:`sha256:${'6'.repeat(64)}`};}
describe('backup expiry evidence',()=>{
 it('strict-reopens named canonical bytes and recomputes their checksum',async()=>{const root=await mkdtemp(join(tmpdir(),'backup-'));roots.push(root);const bytes=`${canonicalProviderJson(backupValue())}\n`;const hash=providerChecksum(Buffer.from(bytes));const name=`${hash.slice(7)}.json`;await writeFile(join(root,name),bytes);expect(await readBackupExpiryEvidence(root,name,new Date('2026-08-30T01:00:00.000Z'))).toMatchObject({checksum:hash,evidence:{backupDisposition:'expires'}});});
 it('rejects unknown fields, expiry, traversal, and symlink substitution',async()=>{const root=await mkdtemp(join(tmpdir(),'backup-'));roots.push(root);const forged={...backupValue(),unknown:true};const bytes=`${canonicalProviderJson(forged)}\n`;const hash=providerChecksum(Buffer.from(bytes));await writeFile(join(root,`${hash.slice(7)}.json`),bytes);await expect(readBackupExpiryEvidence(root,`${hash.slice(7)}.json`,new Date('2026-08-30T01:00:00.000Z'))).rejects.toThrow();await expect(readBackupExpiryEvidence(root,'../bad.json')).rejects.toThrow();const target=join(root,'target');await writeFile(target,'{}\n');const link=`${'a'.repeat(64)}.json`;await symlink(target,join(root,link));await expect(readBackupExpiryEvidence(root,link)).rejects.toThrow(/no-follow|regular/u);});
});
